services:
  db:
    image: postgres
    restart: unless-stopped
    container_name: rustquestdb
    shm_size: 128mb
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
